package dev.jamiecraane.standalonekmmimages
// Generated by CommonImages
data class Image(val name: String)
object Images {
	val IC_BOTTOMMENU_PROFILE: Image = Image("ic_bottommenu_profile")
	val IC_BOTTOMMENU_HOME: Image = Image("ic_bottommenu_home")
	val PNG_ICON: Image = Image("png_icon")
}

